exports.bugData = [
  {
    name: "firefly",
    available: "May 27 - Jun 30",
    peak: "Jun",
    time: "7 PM - 4 AM",
    location: "flying near rivers/near holding ponds",
    spawn: "76%",
    rain: false,
  },
  {
    name: "mosquito",
    available: "Apr 26 - Sep 30",
    peak: "Jul - Aug",
    time: "5 PM - 11 PM",
    location: "flying",
    spawn: "7%",
    rain: true,
  },
  {
    name: "bagworm",
    available: "Sep 26 - Mar 31",
    peak: "Oct - Mar",
    time: "all day",
    location: "in trees",
    spawn: "2%",
    rain: true,
  },
  {
    name: "mole cricket",
    available: "Oct 27 - May 31",
    peak: "Dec - Apr",
    time: "all day",
    location: "Underground",
    spawn: "10%",
    rain: true,
  },
  {
    name: "pill bug",
    available: "all year",
    peak: "all year",
    time: "all day",
    location: "Under rocks",
    spawn: "5%",
    rain: true,
  },
  {
    name: "jewel beetle",
    available: "Jun 26 - Aug 31",
    peak: "Jul - Aug",
    time: "8 AM - 4 PM",
    location: "on trees",
    spawn: "2%",
    rain: true,
  },
  {
    name: "longhorn beetle",
    available: "May 27 - Aug 31",
    peak: "Jun - Jul",
    time: "8 AM - 5 PM",
    location: "on trees",
    spawn: "5%",
    rain: true,
  },
  {
    name: "common butterfly",
    available: "Feb 24 - Oct 31",
    peak: "Apr",
    time: "8 AM - 4 PM",
    location: "flying",
    spawn: "3%",
    rain: false,
  },
  {
    name: "purple butterfly",
    available: "May 27 - Aug 31",
    peak: "Jul - Aug",
    time: "8 AM - 5 PM",
    location: "flying near trees",
    spawn: "2%",
    rain: true,
  },
  {
    name: "tiger butterfly",
    available: "Mar 27 - Sep 30",
    peak: "May - Jun",
    time: "8 AM - 4 PM",
    location: "flying",
    spawn: "3%",
    rain: false,
  },
  {
    name: "yellow butterfly",
    available: "Feb 24 - Oct 31",
    peak: "Apr",
    time: "8 AM - 4 PM",
    location: "flying",
    spawn: "3%",
    rain: false,
  },
  {
    name: "brown cicada",
    available: "Jun 26 - Aug 31",
    peak: "Jul",
    time: "8 AM - 5 PM",
    location: "on trees",
    spawn: "6%",
    rain: true,
  },
  {
    name: "robust cicada",
    available: "Jun 26 - Aug 31",
    peak: "Jul",
    time: "8 AM - 4 PM",
    location: "on trees",
    spawn: "5%",
    rain: true,
  },
  {
    name: "walker cicada",
    available: "Jun 26 - Sep 30",
    peak: "Aug",
    time: "8 AM - 4 PM",
    location: "on trees",
    spawn: "2%",
    rain: true,
  },
  {
    name: "cockroach",
    available: "all year",
    peak: "all year",
    time: "all day",
    location: "on trees/pansies/cosmos/spoiled turnips",
    spawn: "2%",
    rain: true,
  },
  {
    name: "banded dragonfly",
    available: "Jun 26 - Aug 31",
    peak: "Jul - Aug",
    time: "8 AM - 5 PM",
    location: "flying",
    spawn: "5%",
    rain: false,
  },
  {
    name: "common dragonfly",
    available: "Apr 26 - Jul 31",
    peak: "Jun",
    time: "8 AM - 5 PM",
    location: "flying",
    spawn: "8%",
    rain: false,
  },
  {
    name: "darner dragonfly",
    available: "May 27 - Aug 31",
    peak: "Jun",
    time: "8 AM - 5 PM",
    location: "flying",
    spawn: "5%",
    rain: false,
  },
  {
    name: "ladybug",
    available: "Feb 24 - Jul 31",
    peak: "Mar",
    time: "8 AM - 5 PM",
    location: "on pansies/cosmos",
    spawn: "2%",
    rain: false,
  },
  {
    name: "pond skater",
    available: "May 27 - Sep 30",
    peak: "Aug",
    time: "8 AM - 7 PM",
    location: "on the lake/holding ponds",
    spawn: "5%",
    rain: true,
  },
  {
    name: "spider",
    available: "Mar 27 - Sep 30",
    peak: "Apr - Sep",
    time: "all day",
    location: "in trees",
    spawn: "2%",
    rain: true,
  },
  {
    name: "spotted ladybug",
    available: "Feb 24 - Jul 31",
    peak: "Mar",
    time: "8 AM - 5 PM",
    location: "on pansies/cosmos",
    spawn: "2%",
    rain: false,
  },
  {
    name: "drone beetle",
    available: "Jun 26 - Aug 31",
    peak: "Aug",
    time: "all day",
    location: "on trees",
    spawn: "10%",
    rain: true,
  },
  {
    name: "dynastid beetle",
    available: "Jun 26 - Aug 31",
    peak: "Jul - Aug",
    time: "7 PM - 8 AM",
    location: "on trees",
    spawn: "5%",
    rain: true,
  },
  {
    name: "flat stag beetle",
    available: "May 27 - Aug 31",
    peak: "Jul - Aug",
    time: "7 PM - 8 AM",
    location: "on trees",
    spawn: "5%",
    rain: true,
  },
  {
    name: "giant beetle",
    available: "Jun 26 - Aug 31",
    peak: "Jul - Aug",
    time: "11 PM - 8 AM",
    location: "on trees",
    spawn: "1%",
    rain: true,
  },
  {
    name: "mountain beetle",
    available: "Jun 26 - Aug 31",
    peak: "Jul - Aug",
    time: "7 PM - 8 AM",
    location: "on trees",
    spawn: "5%",
    rain: true,
  },
  {
    name: "saw stag beetle",
    available: "Jun 26 - Aug 31",
    peak: "Jul - Aug",
    time: "7 PM - 8 AM",
    location: "on trees",
    spawn: "5%",
    rain: true,
  },
  {
    name: "evening cicada",
    available: "Jun 26 - Aug 31",
    peak: "Jul",
    time: "4 - 8, 16 - 19",
    location: "on trees",
    spawn: "10%",
    rain: true,
  },
  {
    name: "snail",
    available: "Mar 27 - Sep 30",
    peak: "Apr - Sep",
    time: "all day (raining)",
    location: "on flowers",
    spawn: "4%",
    rain: true,
  },
  {
    name: "ant",
    available: "all year",
    peak: "all year",
    time: "all day",
    location: "on candy/spoiled turnips",
    spawn: "100%",
    rain: false,
  },
  {
    name: "cricket",
    available: "Aug 27 - Nov 30",
    peak: "Sep",
    time: "5 PM - 8 AM",
    location: "in bushes",
    spawn: "30%",
    rain: false,
  },
  {
    name: "bell cricket",
    available: "Aug 27 - Oct 31",
    peak: "Sep",
    time: "5 PM - 8 AM",
    location: "in bushes",
    spawn: "10%",
    rain: false,
  },
  {
    name: "pine cricket",
    available: "Aug 27 - Oct 31",
    peak: "Sep",
    time: "5 PM - 8 AM",
    location: "in bushes",
    spawn: "20%",
    rain: false,
  },
  {
    name: "bee",
    available: "all year",
    peak: "all year",
    time: "all day",
    location: "in trees",
    spawn: "5 per day",
    rain: true,
  },
  {
    name: "grasshopper",
    available: "Jul 27 - Sep 30",
    peak: "Sep",
    time: "8 AM - 5 PM",
    location: "in bushes",
    spawn: "11%",
    rain: false,
  },
  {
    name: "long locust",
    available: "Jul 27 - Nov 30",
    peak: "Sep",
    time: "8 AM - 7 PM",
    location: "in bushes",
    spawn: "19%",
    rain: false,
  },
  {
    name: "migratory locust",
    available: "Aug 27 - Nov 30",
    peak: "Sep",
    time: "8 AM - 7 PM",
    location: "on the ground",
    spawn: "19%",
    rain: false,
  },
  {
    name: "mantis",
    available: "Jul 27 - Oct 31",
    peak: "Sep",
    time: "8 AM - 5 PM",
    location: "on pansies/cosmos",
    spawn: "14%",
    rain: false,
  },
  {
    name: "red dragonfly",
    available: "Aug 27 - Oct 31",
    peak: "Oct",
    time: "8 AM - 7 PM",
    location: "flying",
    spawn: "5%",
    rain: false,
  },
];
